### ISSUE TITLE
Use tdp_core extension point to add new LineUp panel button

### ISSUE THREAD

**Issue by thinkh** [Caleydo/tourdino#10]
See if you can add a button using the `EXTENSION_POINT_TDP_RANKING_BUTTON` extension point of tdp_core.

https://github.com/datavisyn/tdp_core/blob/dde24502aabbeca3cd2e6d69edf3303094cc1a6e/src/lineup/internal/LineUpPanelActions.ts#L266-L274

### Definition of Done

- [x] Show calculator button in LineUp panel actions
- [ ] On button click a panel should open and show an example text

**Comment by oltionchampari** [comment]
Included in Caleydo/tourdino#11
