### ISSUE TITLE
Correlation with Rank is slower than originally.

### ISSUE THREAD

**Issue by oltionchampari** [Caleydo/tourdino#34]
While trying to make the Touring Panel work for multiple rankings, a bug was introduced with the below result:

![rank_corrolation](https://user-images.githubusercontent.com/51322092/76081399-4f229680-5fa9-11ea-886f-ce51674c49f0.gif)

**Comment by thinkh** [comment]
Fixed with PR https://github.com/Caleydo/tourdino/pull/35
