### ISSUE TITLE
Identify proxy columns correctly

### ISSUE THREAD

**Issue by oltionchampari** [Caleydo/tourdino#36]
The issue is that the **_score** property is used as an identifier to distinguish between
 database/annotations columns and scores.

https://github.com/Caleydo/tourdino/blob/8a70ec83e29aa1e48dc5ae075ce62dd0b4673ad8/src/RankingAdapter.ts#L34-L36

The above property doesn't exist for added scores through the ordino detail view chooser, which produces the below bug:

![bug_img.gif](https://images.zenhubusercontent.com/5cf50109d8501ed6b9d4b966/611178b9-812b-49d7-815d-a9c0aeaa5212)

**Comment by thinkh** [comment]
Fixed with PR https://github.com/Caleydo/tourdino/pull/37
