### ISSUE TITLE
Remove entries with missing values for all calculations

### ISSUE THREAD

**Issue by thinkh** [Caleydo/tourdino#50]
### Background information

A typical question in Tourdino could be: are the `AA mutated` values of the genes `TP53` and `MDM2` correlated for all cell lines?

When adding these two columns to the list of all cell lines and then checking the similarity of the values for the two genes, one get's the impression that they are highly similar (p < 0.001). However, this is exclusively driven by the fact that almost all cell lines that have a missing value for one gene also have a missing value for the other.

![grafik](https://user-images.githubusercontent.com/10066078/81561625-c0107100-9393-11ea-928f-c0f0b30b1a7d.png)

The user can fix this by removing rows with missing values, however, since this is not obvious it is better to remove these rows automatically in the calculation. **Therefore, please remove entries with missing values in all calculations (for column comparisons as well as row comparisons)**.

If it is easy to implement (< 5h of effort), you can also add a checkbox to allow the user to define whether missing values should be excluded or not (by default they should be excluded).

Thanks!

### Implementation

In order to determine a missing value you can use LineUp's util function [`isMissingValue()`](https://github.com/lineupjs/lineupjs/blob/4976c18e6ddc549217a9700e63a963fbce12416c/src/model/missing.ts#L4-L17).

![grafik](https://user-images.githubusercontent.com/5851088/81720438-b4e63f80-947e-11ea-95cf-1ee8da2ff8fd.png)

If the checkbox is active, all rows with missing values of all columns are filtered out. Otherwise rows with missing values are considered for the calcuation (as it is now). 

Here is the html code that I used for the mock-up above:

```html
<div class="form-group">
	<div class="col-sm-8 col-sm-offset-4">
	  <div class="checkbox">
	    <label>
	      <input type="checkbox">Filter missing values for calculation</label>
	  </div>
	</div>
</div>
```

The additional form group was added to the `div.type.form-horizontal.input`.

**Comment by zichner** [comment]
@thinkh Thanks for the suggestion regarding the UI. This looks like what I had in mind. For consistency with the other UI elements, one could place the text on the left side of the checkbox, but this is a very minor detail.

Regarding the actual implementation there is one main difference to what you wrote
> If the checkbox is active, all rows with missing values of all columns are filtered out. Otherwise rows with missing values are considered for the calcuation (as it is now).

Only missing values of the compared columns should be excluded. So, if I have four columns A, B, C, and D and then compare A vs the other three, the comparison A vs B contains all rows that have values for these two columns (independent of whether there is a value in C).

Does this make sense from your point of view?

**Comment by thinkh** [comment]
> Thanks for the suggestion regarding the UI. This looks like what I had in mind. For consistency with the other UI elements, one could place the text on the left side of the checkbox, but this is a very minor detail.

Would that the question text _Do you want to filter out missing values for the compared columns?_ work for you? Alternative would be _Do you want to exclude missing values for the compared columns?_.

![grafik](https://user-images.githubusercontent.com/5851088/81781614-b5232100-94f8-11ea-9cc6-e25b3ebb53f9.png)


```html
<div class="form-group">
    <label class="col-sm-4 control-label" style="padding-top:.6em" for="tourdino_checkbox">Do you want to filter out missing values for the compared columns?</label>
	<div class="col-sm-8">
	      <input type="checkbox" id="tourdino_checkbox">
	</div>
</div>
```
(Note for the implementation: the `id` attribute of the checkbox must be prefixed with a unique identifier, due to multiple rankings and tourdino instances on the same page.)


> Only missing values of the compared columns should be excluded. So, if I have four columns A, B, C, and D and then compare A vs the other three, the comparison A vs B contains all rows that have values for these two columns (independent of whether there is a value in C).
> Does this make sense from your point of view?

Thanks for the clarification. Yes, I think that makes sense. At the end you only want to filter out missing values for the "active" comparison, i.e., each cell in the result table. For example filter out missing values for the calculation of _Gender_ and _Rank_, then for _Gender_ and _Selection_, and so on.

![grafik](https://user-images.githubusercontent.com/5851088/81781971-62963480-94f9-11ea-8414-1967d7ee8f4b.png)

**Comment by zichner** [comment]
Looks good. Thanks!
For the checkbox text I suggest 
*Do you want to exclude missing values in each comparison?*
which can be used for the column as well as row comparison.

**Comment by oltionchampari** [comment]
Tested the new `RowComparisonTask` against the official deployed tourdino instance, there was no difference to be seen. The filtering also works as expected, the values update accordingly when toggling the filter checkbox.

---

### Before the refactoring

![before_refactoring](https://user-images.githubusercontent.com/51322092/83135477-2b717700-a0e6-11ea-8a26-b50a03379c3e.png)
---
### After the refactoring

![after_refactoring](https://user-images.githubusercontent.com/51322092/83135519-36c4a280-a0e6-11ea-8905-279449cb414c.png)

**Comment by oltionchampari** [comment]
The reason the build fails is because of the import of ` isMissingValue()`, `ValueColumn`. Removing the imports fixes the build. I could not figure out though the reason why that makes the tests fail. I suppose the tourdino webpack/karma config could be the reason.

**Comment by thinkh** [comment]
> Tested the new `RowComparisonTask` against the official deployed tourdino instance, there was no difference to be seen. The filtering also works as expected, the values update accordingly when toggling the filter checkbox.

Great! Thanks for testing. I think we are good go. Could you please file a PR for the feature branch?

> The reason the build fails is because of the import of ` isMissingValue()`, `ValueColumn`. Removing the imports fixes the build. I could not figure out though the reason why that makes the tests fail. I suppose the tourdino webpack/karma config could be the reason.

Thanks for your investigation and the fix. The last commit on the feature branch is not successful. Could you please commit the fix?

**Comment by oltionchampari** [comment]
> > Tested the new `RowComparisonTask` against the official deployed tourdino instance, there was no difference to be seen. The filtering also works as expected, the values update accordingly when toggling the filter checkbox.
> 
> Great! Thanks for testing. I think we are good go. Could you please file a PR for the feature branch?
> 
> > The reason the build fails is because of the import of ` isMissingValue()`, `ValueColumn`. Removing the imports fixes the build. I could not figure out though the reason why that makes the tests fail. I suppose the tourdino webpack/karma config could be the reason.
> 
> Thanks for your investigation and the fix. The last commit on the feature branch is not successful. Could you please commit the fix?

When i tested this yesterday the error was `window is not defined`, removing the LineUp imports fixed the issue. Today the same thing causes locally an error `document is not defined ` when running `npm test `.  So we need to look into this a bit more.

**Comment by thinkh** [comment]
Thanks. I will take a look at this and see how we can fix the tests.

**Comment by thinkh** [comment]
@oltionchampari  I fixed the unit tests in tourdino by moving a function and it's import to a different file. I described the root cause in this commit https://github.com/Caleydo/tourdino/commit/376dc44f078acd0f3e4334d9314fe15f4a614d14. please open a PR for this branch, since the CircleCI build is now successful again. then we can merge the change on Monday into develop. Thanks.

**Comment by thinkh** [comment]
Done with PR https://github.com/Caleydo/tourdino/pull/55.
