### ISSUE TITLE
Boxplots for comparison of sets with same label shows just one set

### ISSUE THREAD

**Issue by keckelt** [Caleydo/tourdino#69]
If two sets with the same label are compared, only one boxplot is shown:
![image](https://user-images.githubusercontent.com/10337788/105022724-6005ba80-5a4a-11eb-8208-a279ef12e859.png)

**Comment by keckelt** [comment]
foxed with #70

**Comment by thinkh** [comment]
@keckelt what is missing in this issue? or was it just reopened by mistake?

**Comment by keckelt** [comment]
Nothing missing. If i remember correctly, I've reopened it because the PR (#70) was only merged into develop.
