### ISSUE TITLE
HTML codes are not displayed correctly 

### ISSUE THREAD

**Issue by keckelt** [Caleydo/tourdino#71]
E.g. _greater than_ symbols:
![image](https://user-images.githubusercontent.com/10337788/104921011-06918300-5999-11eb-933b-143ec53dd2f0.png)

![image](https://user-images.githubusercontent.com/10337788/105020531-b1f91100-5a47-11eb-8e33-0f370a1e7feb.png)

**Comment by thinkh** [comment]
Fixed with https://github.com/Caleydo/tourdino/pull/70
