### ISSUE TITLE
Checkbox in Touring Panel is not indented correctly

### ISSUE THREAD

**Issue by dvvanessastoiber** [Caleydo/tourdino#81]
* Release number or git hash: 1a47c6d6ea8568eccb23e8da41b3f36cf2cd9966
* Web browser version and OS: Chrome 91
* Environment (local or deployed): both

### Steps to reproduce

1. Open Ranking
2. Open Tourdino Panel

### Observed behavior
* Checkbox is not indented correctly but below the label it belongs to
![image (4)](https://user-images.githubusercontent.com/52395160/130835105-2655fce0-1789-40ff-bd9d-f441849461c4.png)

### Expected behavior
* Checkbox is in a row with the label

**Comment by thinkh** [comment]
Fixed with https://github.com/Caleydo/tourdino/pull/82
